# GitHub Actions workflow for PR benchmark comparison
name: Benchmark PR

on:
    pull_request:

    permissions:
    contents: read
pull-requests: write

jobs:
    benchmark:
    runs-on: ubuntu-latest
steps:
    - uses: actions/checkout@v4

- uses: r-lib/actions/setup-r@v2
with:
    use-public-rspm: true

- name: Install dependencies
run: |
    install.packages(c("bench", "devtools", "readr", "dplyr", "ggplot2", "branchmark"))
devtools::install_deps()
shell: Rscript {0}

- name: Run benchmarks
run: |
    library(branchmark)
branchmark_compare()
branchmark_report("benchmark_results.md")
shell: Rscript {0}

- name: Comment PR
uses: actions/github-script@v7
with:
    script: |
    const fs = require('fs');
if (fs.existsSync('benchmark_results.md')) {
    const results = fs.readFileSync('benchmark_results.md', 'utf8');
    github.rest.issues.createComment({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        body: results
    });
}
