# GitHub Actions workflow for generating baselines
name: Generate Baselines

on:
    workflow_dispatch:
    inputs:
    commit_message:
    description: 'Custom commit message for baselines'
required: false
default: 'Update performance baselines'

permissions:
    contents: write

jobs:
    generate-baselines:
    runs-on: ubuntu-latest
steps:
    - uses: actions/checkout@v4
with:
    token: ${{ secrets.GITHUB_TOKEN }}

- uses: r-lib/actions/setup-r@v2
with:
    use-public-rspm: true

- name: Install dependencies
run: |
    install.packages(c("bench", "devtools", "branchmark"))
devtools::install_deps()
shell: Rscript {0}

- name: Generate baselines
run: |
    library(branchmark)
branchmark_baseline(force = TRUE)
shell: Rscript {0}

- name: Commit baselines
run: |
    git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
git config --local user.name "github-actions[bot]"
git add branchmark/baselines/
    if ! git diff --staged --quiet; then
git commit -m "${{ github.event.inputs.commit_message }}"
git push
fi
